const DATA=window.BEAM_XLSM_DATA;
const MATERIALS=DATA.materials,LOAD_CASES=DATA.loadCases,SHAPES=DATA.shapes,DEFAULTS=DATA.defaults;
const $=id=>document.getElementById(id);
function num(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function div(a,b){return b?a/b:NaN}
function isY(a){return String(a||'').startsWith('Y')}
function fmt(v,d=3){if(!Number.isFinite(v))return'-';const av=Math.abs(v);if(av!==0&&(av>=1e7||av<1e-4))return v.toExponential(4);return v.toLocaleString('ja-JP',{maximumFractionDigits:d})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function mat(name){return MATERIALS.find(x=>x.name===name)||MATERIALS[0]}
function shape(){return SHAPES.find(x=>x.name===$('shapePreset').value)||SHAPES[0]}
function manual(){const s=shape();return !s||s.name==='手入力'||$('shapePreset').value==='手入力'}
function populate(){
 $('shapePreset').innerHTML=SHAPES.map(s=>`<option value="${esc(s.name)}">${esc(s.name)}</option>`).join('');
 $('material').innerHTML=MATERIALS.map(m=>`<option value="${esc(m.name)}">${esc(m.name)}</option>`).join('');
 $('loadCase').innerHTML=LOAD_CASES.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')
}
function init(){for(const [k,v] of Object.entries({shapePreset:DEFAULTS.shapePreset,material:DEFAULTS.material,loadCase:DEFAULTS.loadCase,sectionType:DEFAULTS.sectionType,axis:DEFAULTS.axis,deflectionRatio:DEFAULTS.deflectionRatio,spanL:DEFAULTS.spanL,pointLoadP:DEFAULTS.pointLoadP,uniformLoadW:DEFAULTS.uniformLoadW,diameterD:DEFAULTS.diameterD,B:DEFAULTS.B,H:DEFAULTS.H,t1:DEFAULTS.t1,t2:DEFAULTS.t2,gravity:DEFAULTS.gravity})){if($(k))$(k).value=v}applyPreset()}
function applyPreset(){const m=manual(),s=shape();$('material').disabled=!m;$('sectionType').disabled=!m;['B','H','t1','t2','diameterD'].forEach(id=>$(id).disabled=!m);if(!m&&s){$('material').value=s.material||'SS400';$('sectionType').value=s.sectionType||'長方形';$('B').value=s.B??'';$('H').value=s.H??'';$('t1').value=s.t1??'';$('t2').value=s.t2??'';$('diameterD').value=''}}
function inputs(){const s=shape(),m=manual(),st=m?$('sectionType').value:s.sectionType;return{manual:m,shape:s,material:mat(m?$('material').value:s.material),sectionType:st,axis:$('axis').value,L:num($('spanL').value),P:num($('pointLoadP').value),w:num($('uniformLoadW').value),n:num($('deflectionRatio').value,300),D:num($('diameterD').value),B:num($('B').value),H:num($('H').value),t1:num($('t1').value),t2:num($('t2').value),g:num($('gravity').value,9.80665),loadCase:$('loadCase').value}}
function validate(i){const{B,H,t1,t2,D}=i;if(i.L<=0||i.P<0||i.w<0)return'NG';switch(i.sectionType){case'丸棒':return D>0?'OK':'NG';case'長方形':return B>0&&H>0?'OK':'NG';case'L字':return B>0&&H>0&&t1>0&&t2>0&&t1<H&&t2<B?'OK':'NG';case'コの字':return B>0&&H>0&&t1>0&&t2>0&&t1<H&&2*t2<B?'OK':'NG';case'コの字2':return B>0&&H>0&&t1>0&&t2>0&&2*t1<H&&t2<B?'OK':'NG';case'I形鋼':case'H形鋼':return B>0&&H>0&&t1>0&&t2>0&&2*t1<H&&t2<B?'OK':'NG';default:return'NG'}}
function sectionManual(i){const D=i.D,B=i.B,H=i.H,t1=i.t1,t2=i.t2,y=isY(i.axis);let A=NaN,c=NaN,I=NaN,Z=NaN,memo='';
 if(i.sectionType==='丸棒'){A=Math.PI*D**2/4;c=D/2;I=Math.PI*D**4/64;Z=div(I,D/2);memo='丸棒：A=πD²/4、I=πD⁴/64'}
 else if(i.sectionType==='長方形'){A=B*H;c=y?B/2:H/2;I=y?H*B**3/12:B*H**3/12;Z=y?div(I,B/2):div(I,H/2);memo='長方形：X方向はB･H³/12、Y方向はH･B³/12'}
 else if(i.sectionType==='L字'){A=t2*H+B*t1-t2*t1;c=y?div(t2*H*(t2/2)+B*t1*(B/2)-t2*t1*(t2/2),A):div(t2*H*(H/2)+B*t1*(t1/2)-t2*t1*(t1/2),A);I=y?(H*t2**3/12+t2*H*(t2/2-c)**2+t1*B**3/12+B*t1*(B/2-c)**2-t1*t2**3/12-t2*t1*(t2/2-c)**2):(t2*H**3/12+t2*H*(H/2-c)**2+B*t1**3/12+B*t1*(t1/2-c)**2-t2*t1**3/12-t2*t1*(t1/2-c)**2);Z=y?div(I,Math.max(c,B-c)):div(I,Math.max(c,H-c));memo='L字：縦板＋横板から重複部を差し引く簡易式'}
 else if(i.sectionType==='コの字'){A=B*t1+2*t2*(H-t1);const q=B*t1*(H-t1/2)+2*t2*(H-t1)*((H-t1)/2);c=y?B/2:div(q,A);I=y?(t1*B**3/12+2*((H-t1)*t2**3/12+t2*(H-t1)*(B/2-t2/2)**2)):(B*t1**3/12+B*t1*(H-t1/2-c)**2+2*(t2*(H-t1)**3/12+t2*(H-t1)*(((H-t1)/2)-c)**2));Z=y?div(I,B/2):div(I,Math.max(c,H-c));memo='コの字：上板＋左右脚として計算'}
 else if(i.sectionType==='コの字2'){A=t2*H+2*(B-t2)*t1;const q=t2*H*(t2/2)+2*(B-t2)*t1*(t2+(B-t2)/2);c=y?div(q,A):H/2;I=y?(H*t2**3/12+t2*H*(c-t2/2)**2+2*(t1*(B-t2)**3/12+(B-t2)*t1*(c-(t2+(B-t2)/2))**2)):(t2*H**3/12+2*((B-t2)*t1**3/12+(B-t2)*t1*(((H-t1)/2)**2)));Z=y?div(I,Math.max(c,B-c)):div(I,H/2);memo='コの字2：縦板＋上下横板として計算'}
 else if(i.sectionType==='I形鋼'||i.sectionType==='H形鋼'){A=2*B*t1+t2*(H-2*t1);c=y?B/2:H/2;I=y?2*(t1*B**3/12)+(H-2*t1)*t2**3/12:2*(B*t1**3/12+B*t1*((H-t1)/2)**2)+t2*(H-2*t1)**3/12;Z=y?div(I,B/2):div(I,H/2);memo=i.sectionType+'：左右対称断面として概算'}
 return{A,c,I,Z,memo,fromDb:false}}
function section(i){if(i.manual)return sectionManual(i);const s=i.shape,y=isY(i.axis),man=sectionManual(i);return{A:(s.areaCm2||0)*100,I:(y?s.IyCm4:s.IxCm4)*10000,Z:(y?s.ZyCm3:s.ZxCm3)*1000,c:man.c,memo:'形鋼プリセット：A・I・Zは形鋼DBの表値を使用',fromDb:true}}
function calc(){const i=inputs(),sec=section(i),E=i.material.E,d=i.material.density,Fy=i.material.yieldStress;const selfW=sec.A*d*i.g/1e9,totalW=i.w+selfW,L=i.L,P=i.P,w=i.w,I=sec.I;let M=NaN,dLoad=NaN,dSelf=NaN;
 if(i.loadCase==='両端支持・中央集中荷重'){M=P*L/4+selfW*L**2/8;dLoad=div(P*L**3,48*E*I);dSelf=div(5*selfW*L**4,384*E*I)}
 else if(i.loadCase==='両端支持・等分布荷重'){M=totalW*L**2/8;dLoad=div(5*w*L**4,384*E*I);dSelf=div(5*selfW*L**4,384*E*I)}
 else if(i.loadCase==='片持ち・先端集中荷重'){M=P*L+selfW*L**2/2;dLoad=div(P*L**3,3*E*I);dSelf=div(selfW*L**4,8*E*I)}
 else if(i.loadCase==='片持ち・等分布荷重'){M=totalW*L**2/2;dLoad=div(w*L**4,8*E*I);dSelf=div(selfW*L**4,8*E*I)}
 else if(i.loadCase==='両端固定・中央集中荷重'){M=P*L/8+selfW*L**2/12;dLoad=div(P*L**3,192*E*I);dSelf=div(selfW*L**4,384*E*I)}
 else if(i.loadCase==='両端固定・等分布荷重'){M=totalW*L**2/12;dLoad=div(w*L**4,384*E*I);dSelf=div(selfW*L**4,384*E*I)}
 const stress=div(M,sec.Z),safety=div(Fy,stress),dTotal=dLoad+dSelf,dAllow=div(L,i.n),mass=sec.A*L*d/1e9;const sectionCheck=validate(i),stressJudge=safety>=1?'OK':'NG',deflectionJudge=dTotal<=dAllow?'OK':'NG',overall=sectionCheck==='OK'&&stressJudge==='OK'&&deflectionJudge==='OK'?'OK':'NG';const usedLoad=i.loadCase.includes('等分布')?i.w:i.P,usedUnit=i.loadCase.includes('等分布')?'N/mm':'N';return{i,sec,E,density:d,Fy,selfW,totalW,M,stress,safety,dLoad,dSelf,dTotal,dAllow,mass,sectionCheck,stressJudge,deflectionJudge,overall,usedLoad,usedUnit}}
function badge(el,text,cls){el.className=el.classList.contains('big-badge')?'big-badge':'badge';el.textContent=text;if(cls)el.classList.add(cls)}
function render(){const r=calc();badge($('shapeCheckBadge'),'断面判定：'+r.sectionCheck,r.sectionCheck==='OK'?'ok':'ng');badge($('overallBadge'),r.overall,r.overall==='OK'?'ok':'ng');[['rE',r.E,0],['rDensity',r.density,0],['rYield',r.Fy,3],['rArea',r.sec.A,3],['rCentroid',r.sec.c,3],['rI',r.sec.I,3],['rZ',r.sec.Z,3],['rUsedLoad',r.usedLoad,6],['rSelfW',r.selfW,9],['rTotalW',r.totalW,9],['rM',r.M,3],['rStress',r.stress,3],['rSafety',r.safety,3],['rDefLoad',r.dLoad,6],['rDefSelf',r.dSelf,6],['rDefTotal',r.dTotal,6],['rDefAllow',r.dAllow,3],['rMass',r.mass,6]].forEach(a=>$(a[0]).textContent=fmt(a[1],a[2]));$('rUsedLoadUnit').textContent=r.usedUnit;badge($('stressJudge'),'応力判定：'+r.stressJudge,r.stressJudge==='OK'?'ok':'ng');badge($('deflectionJudge'),'たわみ判定：'+r.deflectionJudge,r.deflectionJudge==='OK'?'ok':'ng');const ci=LOAD_CASES.find(c=>c.name===r.i.loadCase)||{};$('formulaMemo').textContent=`支持・荷重ケース：${r.i.loadCase}\nExcelケースDB：Mmax=${ci.momentFormula||'-'} / δmax=${ci.deflectionFormula||'-'}\n断面：${r.i.manual?'手入力':r.i.shape.name} / ${r.i.sectionType} / ${r.i.axis}\n\n自重等分布荷重 w_self = A × 密度 × g / 1,000,000,000\n= ${fmt(r.sec.A,6)} × ${fmt(r.density,6)} × ${fmt(r.i.g,6)} / 1,000,000,000\n= ${fmt(r.selfW,9)} N/mm\n\n合計等分布荷重 w_total = 外力w + w_self\n= ${fmt(r.i.w,9)} + ${fmt(r.selfW,9)}\n= ${fmt(r.totalW,9)} N/mm\n\n最大曲げモーメント Mmax = ${fmt(r.M,6)} N･mm\n最大曲げ応力 σ = Mmax / Z = ${fmt(r.M,6)} / ${fmt(r.sec.Z,6)} = ${fmt(r.stress,6)} N/mm²\n安全率 = 降伏/耐力 / σ = ${fmt(r.Fy,6)} / ${fmt(r.stress,6)} = ${fmt(r.safety,6)}\n\n外力たわみ δ_load = ${fmt(r.dLoad,9)} mm\n自重たわみ δ_self = ${fmt(r.dSelf,9)} mm\n最大たわみ δ_total = ${fmt(r.dTotal,9)} mm\n許容たわみ = L/n = ${fmt(r.i.L,6)} / ${fmt(r.i.n,6)} = ${fmt(r.dAllow,6)} mm\n\n断面メモ：${r.sec.memo}`;$('sectionMemo').textContent=r.sec.memo;drawSection(r.i,r.sec);drawMoment(r);table()}
function canvasSize(c){const ratio=window.devicePixelRatio||1,w=Math.max(1,Math.round(c.clientWidth||c.width)),h=Math.max(1,Math.round(c.clientHeight||c.height));if(c.width!==Math.round(w*ratio)||c.height!==Math.round(h*ratio)){c.width=Math.round(w*ratio);c.height=Math.round(h*ratio)}const ctx=c.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);return{ctx,w,h}}
function rect(ctx,x,y,w,h){ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h)}
function dim(ctx,x1,y1,x2,y2,t,vertical=false){ctx.save();ctx.strokeStyle=ctx.fillStyle='#2563eb';ctx.lineWidth=1.5;ctx.font='12px sans-serif';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();if(vertical){ctx.beginPath();ctx.moveTo(x1-4,y1);ctx.lineTo(x1+4,y1);ctx.moveTo(x2-4,y2);ctx.lineTo(x2+4,y2);ctx.stroke();ctx.save();ctx.translate(x1+12,(y1+y2)/2);ctx.rotate(-Math.PI/2);ctx.fillText(t,-ctx.measureText(t).width/2,0);ctx.restore()}else{ctx.beginPath();ctx.moveTo(x1,y1-4);ctx.lineTo(x1,y1+4);ctx.moveTo(x2,y2-4);ctx.lineTo(x2,y2+4);ctx.stroke();ctx.fillText(t,(x1+x2)/2-ctx.measureText(t).width/2,y1-6)}ctx.restore()}
function drawSection(i,sec){const c=$('sectionCanvas'),s=canvasSize(c),ctx=s.ctx,W=s.w,Hc=s.h;ctx.clearRect(0,0,W,Hc);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,Hc);const dw=Math.max(i.B||i.D||1,1),dh=Math.max(i.H||i.D||1,1),scale=Math.min((W-100)/dw,(Hc-70)/dh)*.9,x0=(W-dw*scale)/2,y0=(Hc-dh*scale)/2,B=i.B*scale,H=i.H*scale,t1=i.t1*scale,t2=i.t2*scale,D=i.D*scale;ctx.strokeStyle='#0f172a';ctx.lineWidth=2;ctx.fillStyle='#dbeafe';if(i.sectionType==='丸棒'){ctx.beginPath();ctx.arc(W/2,Hc/2,D/2,0,Math.PI*2);ctx.fill();ctx.stroke()}else if(i.sectionType==='長方形'){rect(ctx,x0,y0,B,H)}else if(i.sectionType==='L字'){rect(ctx,x0,y0,t2,H);rect(ctx,x0,y0+H-t1,B,t1)}else if(i.sectionType==='コの字'){rect(ctx,x0,y0,B,t1);rect(ctx,x0,y0+t1,t2,H-t1);rect(ctx,x0+B-t2,y0+t1,t2,H-t1)}else if(i.sectionType==='コの字2'){rect(ctx,x0,y0,t2,H);rect(ctx,x0+t2,y0,B-t2,t1);rect(ctx,x0+t2,y0+H-t1,B-t2,t1)}else{rect(ctx,x0,y0,B,t1);rect(ctx,x0+(B-t2)/2,y0+t1,t2,H-2*t1);rect(ctx,x0,y0+H-t1,B,t1)}ctx.save();ctx.setLineDash([6,5]);ctx.strokeStyle='#c62828';ctx.fillStyle='#c62828';ctx.font='12px sans-serif';if(Number.isFinite(sec.c)){if(isY(i.axis)){const cx=x0+sec.c*scale;ctx.beginPath();ctx.moveTo(cx,16);ctx.lineTo(cx,Hc-16);ctx.stroke();ctx.fillText(`Y方向 中立軸 c=${fmt(sec.c,2)}mm`,16,20)}else{const ref=i.sectionType==='丸棒'?i.D:i.H,cy=y0+(ref-sec.c)*scale;ctx.beginPath();ctx.moveTo(16,cy);ctx.lineTo(W-16,cy);ctx.stroke();ctx.fillText(`X方向 中立軸 c=${fmt(sec.c,2)}mm`,16,20)}}ctx.restore();if(i.sectionType==='丸棒'){dim(ctx,W/2-D/2,Hc-24,W/2+D/2,Hc-24,`D=${fmt(i.D,3)} mm`)}else{dim(ctx,x0,Hc-22,x0+B,Hc-22,`B=${fmt(i.B,3)} mm`);dim(ctx,x0-20,y0,x0-20,y0+H,`H=${fmt(i.H,3)} mm`,true);if(i.t1>0)dim(ctx,x0+B+14,y0,x0+B+14,y0+t1,`t1=${fmt(i.t1,3)}`,true);if(i.t2>0)dim(ctx,x0,y0-10,x0+t2,y0-10,`t2=${fmt(i.t2,3)}`)}ctx.fillStyle='#334155';ctx.font='12px sans-serif';ctx.fillText(`断面形状：${i.sectionType}`,16,Hc-8)}
function arrow(ctx,x1,y1,x2,y2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const a=Math.atan2(y2-y1,x2-x1),h=7;ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-h*Math.cos(a-Math.PI/6),y2-h*Math.sin(a-Math.PI/6));ctx.lineTo(x2-h*Math.cos(a+Math.PI/6),y2-h*Math.sin(a+Math.PI/6));ctx.closePath();ctx.fill()}
function support(ctx,x,y,fixed){ctx.strokeStyle='#111827';ctx.fillStyle='#e5e7eb';if(fixed){ctx.fillRect(x-18,y-28,10,56);ctx.strokeRect(x-18,y-28,10,56)}else{ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-15,y+28);ctx.lineTo(x+15,y+28);ctx.closePath();ctx.fill();ctx.stroke()}}
function mshape(c,t){if(c==='両端支持・中央集中荷重')return t<=.5?t/.5:(1-t)/.5;if(c==='両端支持・等分布荷重')return 4*t*(1-t);if(c==='片持ち・先端集中荷重')return 1-t;if(c==='片持ち・等分布荷重')return(1-t)**2;if(c==='両端固定・中央集中荷重')return t<=.5?1-2*t:2*t-1;if(c==='両端固定・等分布荷重')return Math.max(Math.abs(1-6*t+6*t*t),.5*4*t*(1-t));return 0}
function drawMoment(r){const c=$('momentCanvas'),s=canvasSize(c),ctx=s.ctx,W=s.w,H=s.h;ctx.clearRect(0,0,W,H);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);const x0=Math.max(45,W*.08),x1=W-x0,span=x1-x0,beamY=Math.max(52,H*.16),baseY=Math.max(115,H*.46),amp=Math.max(45,Math.min(H*.33,H-70-baseY));ctx.strokeStyle='#111827';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(x0,beamY);ctx.lineTo(x1,beamY);ctx.stroke();ctx.fillStyle='#111827';ctx.font='12px sans-serif';ctx.fillText(`L=${fmt(r.i.L,0)} mm`,x1-88,beamY-16);support(ctx,x0,beamY,r.i.loadCase.startsWith('片持ち'));if(!r.i.loadCase.startsWith('片持ち'))support(ctx,x1,beamY,false);ctx.strokeStyle=ctx.fillStyle='#2563eb';if(r.i.loadCase.includes('集中')){const lx=r.i.loadCase.startsWith('片持ち')?x1:(x0+x1)/2;arrow(ctx,lx,Math.max(18,beamY-48),lx,beamY-6);ctx.fillText(`P=${fmt(r.i.P,1)} N`,lx-34,Math.max(14,beamY-52))}if(r.selfW>0||r.i.loadCase.includes('等分布')){const top=Math.max(25,beamY-36);for(let k=0;k<=10;k++){const lx=x0+span*k/10;arrow(ctx,lx,top,lx,beamY-6)}ctx.fillText(`w_total=${fmt(r.totalW,6)} N/mm`,x0+8,top-4)}ctx.strokeStyle='#c62828';ctx.fillStyle='rgba(198,40,40,.12)';ctx.beginPath();ctx.moveTo(x0,baseY);for(let k=0;k<=120;k++){const t=k/120;ctx.lineTo(x0+span*t,baseY+mshape(r.i.loadCase,t)*amp)}ctx.lineTo(x1,baseY);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(x0,baseY);for(let k=0;k<=120;k++){const t=k/120;ctx.lineTo(x0+span*t,baseY+mshape(r.i.loadCase,t)*amp)}ctx.stroke();ctx.strokeStyle='#111827';ctx.beginPath();ctx.moveTo(x0,baseY);ctx.lineTo(x1,baseY);ctx.stroke();ctx.fillStyle='#111827';ctx.fillText(`Mmax=${fmt(r.M,2)} N･mm`,x0,H-26);ctx.fillText('簡易図：最大値は上記計算結果、図形は代表形状です',x0,H-9)}
function table(){const tb=document.querySelector('#shapeTable tbody');if(!tb)return;const q=($('shapeFilter')?.value||'').toLowerCase();tb.innerHTML=SHAPES.filter(s=>(s.name+s.sectionType+s.material).toLowerCase().includes(q)).map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.material)}</td><td>${esc(s.sectionType)}</td><td>${s.B??''}</td><td>${s.H??''}</td><td>${s.t2??''}</td><td>${s.t1??''}</td><td>${s.areaCm2??''}</td><td>${s.massKgM??''}</td><td>${s.IxCm4??''}</td><td>${s.IyCm4??''}</td><td>${s.ZxCm3??''}</td><td>${s.ZyCm3??''}</td></tr>`).join('')}
function saveCsv(){const r=calc(),rows=[['項目','値'],['材料',r.i.material.name],['断面',r.i.manual?'手入力':r.i.shape.name],['支持・荷重ケース',r.i.loadCase],['断面積A',r.sec.A],['I',r.sec.I],['Z',r.sec.Z],['Mmax',r.M],['応力',r.stress],['安全率',r.safety],['最大たわみ',r.dTotal],['許容たわみ',r.dAllow],['判定',r.overall]];download('beam_strength_result.csv','\ufeff'+rows.map(a=>a.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}
function saveJson(){const i=inputs();download('beam_strength_input.json',JSON.stringify(i,null,2),'application/json')}
function download(name,content,type){const b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function toggleLayoutMode(){const p=document.querySelector('.page'),b=$('layoutBtn');if(!p||!b)return;const lr=p.classList.contains('layout-left-right');p.classList.toggle('layout-left-right',!lr);p.classList.toggle('layout-top-bottom',lr);b.textContent=lr?'左右表示':'上下表示';requestAnimationFrame(render)}
function bind(){['shapePreset','material','loadCase','sectionType','axis','deflectionRatio','spanL','pointLoadP','uniformLoadW','gravity','diameterD','B','H','t1','t2'].forEach(id=>{$(id).addEventListener('input',()=>{if(id==='shapePreset')applyPreset();render()});$(id).addEventListener('change',()=>{if(id==='shapePreset')applyPreset();render()})});$('shapeFilter')?.addEventListener('input',table);$('printBtn').addEventListener('click',()=>window.print());$('csvBtn').addEventListener('click',saveCsv);$('jsonBtn').addEventListener('click',saveJson);$('layoutBtn').addEventListener('click',toggleLayoutMode);$('resetBtn').addEventListener('click',()=>{init();render()});window.addEventListener('resize',render)}
populate();init();bind();render();
